services:
  # React Frontend Service (Served via Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: keyofhistory-frontend
    ports:
      - "3000:80" # Expose HTTP port 80 as local 3000
    networks:
      - keyofhistory-network

networks:
  keyofhistory-network:
    driver: bridge
