apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keyofhistory-ingress
  namespace: keyofhistory-prod
  annotations:
    # No global rewrite-target is needed because Spring Boot controllers expect the /api prefix
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: keyofhistory.local # Local production simulation hostname
      http:
        paths:
          # Route all traffic to Nginx serving React static assets
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
