apiVersion: v1
kind: Namespace
metadata:
  name: keyofhistory-test
  labels:
    environment: test
---
apiVersion: v1
kind: Namespace
metadata:
  name: keyofhistory-prod
  labels:
    environment: production
